version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: veilsupport_db
    environment:
      POSTGRES_DB: veilsupport
      POSTGRES_USER: veiluser
      POSTGRES_PASSWORD: veilpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U veiluser -d veilsupport"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_test:
    image: postgres:15-alpine
    container_name: veilsupport_test_db
    environment:
      POSTGRES_DB: veilsupport_test
      POSTGRES_USER: veiluser
      POSTGRES_PASSWORD: veilpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U veiluser -d veilsupport_test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  postgres_test_data: