services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: veilsupport
      POSTGRES_USER: veiluser
      POSTGRES_PASSWORD: veilpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://veiluser:veilpass@postgres/veilsupport?sslmode=disable
      JWT_SECRET: ${JWT_SECRET}
      XMPP_SERVER: ${XMPP_SERVER}
      XMPP_CONNECTION_JID: ${XMPP_CONNECTION_JID}
      XMPP_CONNECTION_PASSWORD: ${XMPP_CONNECTION_PASSWORD}
      XMPP_ADMIN_JID: ${XMPP_ADMIN_JID}
      XMPP_ADMIN_PASSWORD: ${XMPP_ADMIN_PASSWORD}
    ports:
      - "8080:8080"

volumes:
  postgres_data: