server:
  port: "8080"
  host: "localhost"
  tor_proxy: "" # Optional: socks5://127.0.0.1:9050

xmpp:
  server: "localhost:5222"
  admin: "admin@localhost"
  password: "admin_password_here"
  domain: "localhost"

database:
  host: "localhost"
  port: 5432
  user: "veilsupport"
  password: "your_db_password_here"
  db_name: "veilsupport"
  ssl_mode: "disable"

jwt:
  secret: "your_jwt_secret_key_here_make_it_long_and_random"
  ttl: 3600 # 1 hour

redis:
  url: "redis://localhost:6379"